### ISSUE TITLE
[FeatureRequest] Show/Hide menu

### ISSUE THREAD

**Issue by 17twenty** [lucperkins/bulma-dashboard#4]
Thanks for putting this together - I ended up converting it to scss to match my existing setup but it worked well.

Do you have plans to provide a way to show/hide the side panel on a click/class mainly so I can show/hide it on mobile.

By default, your example also hides the navbar on mobile which can be a pain!

**Comment by lucperkins** [comment]
@17twenty You should be able to seamlessly intermix `.sass` and `.scss` files in a Sass project. Is there something about your setup that doesn't allow for that?

As for the feature request, there unfortunately isn't really a way to do that using Sass/CSS. You'll need to use jQuery or another JS library to make that happen. You could set `display: none` on the sidebar and do something like this (in jQuery):

```javascript
$('#sidebar-toggler').click(function() {
  $('#sidebar').toggle();
}
```

**Comment by 17twenty** [comment]
just following up . https://codepen.io/ScintillaLuz/pen/HxzED - nice example of using a checkbox to get it done!

**Comment by lucperkins** [comment]
@17twenty The issue is that it requires the button to be placed outside of both the sidebar and the "main" component. In the example you provided, the "close" button is outside both the `.sidebar` and the `.portfolio` and given absolute positioning. Otherwise, the checkbox method doesn't work. I prefer to let people put the trigger wherever they like.
